### ISSUE TITLE
Sugar ignores main

### ISSUE THREAD

**Issue by Ry6000** [ry60003333/grapes-of-math#29]
Please fix to make activity work

**Comment by sctjkc01** [comment]
Easy Fix.  https://github.com/ry60003333/grapes-of-math/blob/master/grapes.py#L14 - grapes.**init**(self,debug = false)

**Comment by Ry6000** [comment]
Initial problem resolved, now we have another one:
![screen shot 2015-12-15 at 7 09 25 pm](https://cloud.githubusercontent.com/assets/3422003/11828104/673ca75c-a35f-11e5-8b40-f4a552385122.png)

**Comment by Ry6000** [comment]
Fixed!
